---
version: '3'
services:
  freqtrade2:
    image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    restart: unless-stopped
    container_name: freqtrade2
    volumes:
      - ./${USER_DATA_DIR}:/freqtrade/${USER_DATA_DIR}
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    #ports:
    #  - "0.0.0.0:8081:8081"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/${USER_DATA_DIR}/logs/freqtrade.log
      --db-url sqlite:////freqtrade/${USER_DATA_DIR}/${DB_FILE}
      --config /freqtrade/${USER_DATA_DIR}/${CONFIG_FILE_NAME}
      --strategy ${STRATEGY_NAME} --strategy-path /freqtrade/${USER_DATA_DIR}/
  freqtrade3:
    image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    restart: unless-stopped
    container_name: freqtrade3
    volumes:
      - ./${USER_DATA_DIR3}:/freqtrade/${USER_DATA_DIR3}
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    #ports:
    #  - "0.0.0.0:8081:8081"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/${USER_DATA_DIR3}/logs/freqtrade.log
      --db-url sqlite:////freqtrade/${USER_DATA_DIR3}/${DB_FILE3}
      --config /freqtrade/${USER_DATA_DIR3}/${CONFIG_FILE_NAME3}
      --strategy ${STRATEGY_NAME3} --strategy-path /freqtrade/${USER_DATA_DIR3}/