---
version: '3'
services:
  freqtrade:
#    image: freqtradeorg/freqtrade:custom
#    build:
#      context: .
#      dockerfile: "./docker/Dockerfile.technical"
    # image: freqtradeorg/freqtrade:stable
    image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
#     build:
#       context: .
#       dockerfile: "./docker/Dockerfile.technical"
    restart: unless-stopped
    container_name: freqtrade2
    volumes:
      - ./${USER_DATA_DIR}:/freqtrade/${USER_DATA_DIR}
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "0.0.0.0:8081:8081"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/${USER_DATA_DIR}/logs/freqtrade.log
      --db-url sqlite:////freqtrade/${USER_DATA_DIR}/${DB_FILE}
      --config /freqtrade/${USER_DATA_DIR}/${CONFIG_FILE_NAME}
      --strategy ${STRATEGY_NAME} --strategy-path /freqtrade/${USER_DATA_DIR}/