version: "3"

services:

  mongo:

    image: mongo

    ports:

      - "27017:27017"

    volumes:

      - zenbotmongovolume:/data/db


  mongoexpress:

    image: mongo-express

    ports:

      - "8081:8081"

    environment:

      - ME_CONFIG_OPTIONS_EDITORTHEME=monokai

    links:

      - mongo

      

volumes:

  zenbotmongovolume:
